import type {
  PersonalInfo,
  Skill,
  Project,
  TimelineItem,
  Certificate,
  Service,
  SocialLink,
} from '@/types';

export const personalInfo: PersonalInfo = {
  name: 'Robert Nicolae Floria',
  title: 'Software Engineer',
  subtitle:
    'React.js | React Native (Expo) | Next.js | NestJS | Node.js | TypeScript | AI Integration',
  bio: 'Innovative Software Engineer with 3+ years of experience in building scalable web and mobile applications using React.js, Next.js, React Native (Expo), TypeScript, Node.js, NestJS, ASP.NET Core, and AI-powered features. Skilled in CI/CD automation (GitHub Actions, Jenkins), cloud deployments (Firebase, Railway, AWS), and containerization (Docker). Passionate about delivering high-performance, user-centric solutions and driving AI adoption in modern development workflows.',
  about:
    'I am a passionate Software Engineer with a strong background in full-stack web and mobile development. My expertise spans React.js, Next.js, React Native (Expo), and TypeScript, complemented by solid experience in backend technologies like Node.js and NestJS. I thrive on building scalable, high-performance applications and integrating AI-powered features to deliver innovative solutions. With a proven track record in CI/CD automation, cloud deployments, and containerization, I am committed to driving modern development practices and creating impactful user experiences.',
  email: 'robertfloria27@gmail.com',
  phone: '+40 745 174 991',
  location: 'Cluj-Napoca, Romania',
  age: '26',
  education: 'Bachelor of Software Engineering',
  university: 'Technical University of Cluj-Napoca',
  profileImage: '/images/profile/profile.png',
};

export const skills: Skill[] = [
  {
    name: 'React.js',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Fullscreen',
    yearsOfExperience: 3,
  },
  {
    name: 'Next.js',
    category: 'Frontend',
    proficiency: 90,
    iconKey: 'Layout',
    yearsOfExperience: 1,
  },
  {
    name: 'React Native (Expo)',
    category: 'Frontend',
    proficiency: 90,
    iconKey: 'Smartphone',
    yearsOfExperience: 2,
  },
  {
    name: 'TypeScript',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 3,
  },
  {
    name: 'JavaScript',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 4,
  },
  {
    name: 'HTML5 & CSS/SASS',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code2',
    yearsOfExperience: 4,
  },
  {
    name: 'Node.js',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'NestJS',
    category: 'Backend',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 2,
  },
  {
    name: 'ASP.NET Core',
    category: 'Backend',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'SQL Server',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 3,
  },
  {
    name: 'MySQL',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 3,
  },
  {
    name: 'Docker',
    category: 'DevOps',
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 2,
  },
  {
    name: 'GitHub Actions',
    category: 'DevOps',
    proficiency: 90,
    iconKey: 'GitBranch',
    yearsOfExperience: 2,
  },
  {
    name: 'Jenkins',
    category: 'DevOps',
    proficiency: 85,
    iconKey: 'GitBranch',
    yearsOfExperience: 2,
  },
  {
    name: 'OpenAI API',
    category: 'AI',
    proficiency: 90,
    iconKey: 'Bot',
    yearsOfExperience: 1,
  },
  // Tools
  {
    name: 'GitHub Copilot',
    category: 'Tools',
    proficiency: 90,
    iconKey: 'Github',
    yearsOfExperience: 2,
  },
  {
    name: 'MCP Servers',
    category: 'Tools',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 1,
  },
  {
    name: 'Prompt Engineering',
    category: 'Tools',
    proficiency: 90,
    iconKey: 'Edit3',
    yearsOfExperience: 1,
  },
];

export const timeline: TimelineItem[] = [
  {
    id: '1',
    title: 'Computer Science High School',
    organization: 'High School',
    startDate: '2014',
    endDate: '2018',
    description: 'Computer science profile with focus on programming fundamentals.',
    type: 'education',
    location: 'Romania',
  },
  {
    id: '2',
    title: 'Bachelor of Software Engineering',
    organization: 'Technical University of Cluj-Napoca',
    startDate: 'October 2018',
    endDate: 'October 2022',
    description:
      'Faculty of Automation and Computer Science. Graduated with Software Engineer diploma.',
    type: 'education',
    location: 'Cluj-Napoca, Romania',
  },
  {
    id: '3',
    title: 'Full-Stack Software Developer',
    organization: 'Transilvania Bank',
    startDate: 'September 2022',
    endDate: 'Present',
    description:
      'Led frontend development for React.js applications using TypeScript/JavaScript. Implemented CI/CD pipelines with Jenkins, reducing deployment time by 30%. Contributed to ASP.NET Core backend using SOLID principles and clean architecture. Organized AI workshops and promoted GitHub Copilot and MCP servers to accelerate team productivity. Technologies: ReactJS 18, TypeScript, ASP.NET Core 8, SQL Server, JavaScript, HTML5, CSS/SASS.',
    type: 'work',
    location: 'Cluj-Napoca, Romania',
    current: true,
  },
  {
    id: '4',
    title: 'Freelance Software Developer',
    organization: 'Self-Employed',
    startDate: 'August 2025',
    endDate: 'Present',
    description:
      'Delivered cross-platform mobile applications with React Native (Expo), published to Google Play and App Store. Implemented OAuth 2.0 authentication (Firebase) and In-App Purchases for subscription models. Built full-stack web applications with React.js frontend and Node.js/NestJS backends. Designed and optimized relational databases (MySQL, Transact-SQL) and automated deployments with GitHub Actions, Firebase Hosting, Railway, and Docker.',
    type: 'work',
    location: 'Remote',
    current: true,
  },
];

export const projects: Project[] = [
  {
    id: '1',
    title: 'Mental Health Mobile App – AI Assistant',
    description:
      'Cross-platform mobile application (Expo) featuring an AI-powered chatbot for personalized mental health guidance, secure OAuth authentication, and in-app purchases. Published to Google Play and Apple App Store.',
    technologies: [
      'React Native (Expo)',
      'TypeScript',
      'OpenAI API',
      'Node.js',
      'Express.js',
      'Firebase',
      'OAuth 2.0',
      'Google Pay',
      'Apple Pay',
      'Railway',
      'Docker',
      'Jest Testing Library',
      'AWS S3',
      'CI-CD: GitHub Actions & Google Play Console & Apple App Store Connect',
    ],
    features: [
      'AI chatbot using OpenAI API for personalized mental health guidance',
      'Secure OAuth authentication (Google & Apple) with Firebase integration',
      'In-App Purchases and subscription flows using Google Pay and Apple Pay',
      'Backend containerized with Docker and deployed on Railway',
      'AWS S3 for media storage and Firebase Cloud Messaging for notifications',
      'Published to Google Play and Apple App Store',
    ],
    imageUrl: '/images/projects/mobile-app/mento_recommendation.png',
    images: [
      '/images/projects/mobile-app/home.png',
      '/images/projects/mobile-app/mento_presentation.png',
      '/images/projects/mobile-app/mento_recommendation.png',
      '/images/projects/mobile-app/chatbot.png',
      '/images/projects/mobile-app/breathing.png',
      '/images/projects/mobile-app/meditation.png',
      '/images/projects/mobile-app/charts.png',
      '/images/projects/mobile-app/logs.png',
      '/images/projects/mobile-app/awards.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Mobile',
    featured: true,
  },
  {
    id: '2',
    title: 'Guaranteed Loan Management System',
    description:
      'Microservices platform for secured loan management with compliance, automated origination, and risk scoring; focused on reliability and maintainability for financial environments.',
    technologies: [
      'React.js',
      'TypeScript',
      'ASP.NET Core',
      'SQL Server',
      'Jest Testing Library',
      'CI-CD: Jenkins',
    ],
    features: [
      'Automated loan origination and risk scoring',
      'Repayment tracking reducing manual workload by 40%',
      'CI/CD pipelines using Jenkins',
      'Microservices architecture for scalability',
      'Production-ready financial system with compliance',
    ],
    imageUrl: '/images/projects/loan-portfolio/HomePage.png',
    images: [
      '/images/projects/loan-portfolio/HomePage.png',
      '/images/projects/loan-portfolio/CreditRequestPage.png',
      '/images/projects/loan-portfolio/CreditDetailsPage.png',
      '/images/projects/loan-portfolio/Filters.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Web',
    featured: true,
  },
  {
    id: '3',
    title: 'AI Adoption Initiative for Frontend Teams',
    description:
      'Company-wide program to integrate AI tooling and workflows (Copilot, OpenAI) into frontend teams, including demos, automation and workshops to accelerate development.',
    technologies: [
      'React.js',
      'TypeScript',
      'GitHub Copilot',
      'MCP Servers',
      'OpenAI API',
      'Figma',
    ],
    features: [
      'Demo applications showcasing Copilot-assisted coding and AI-driven patterns',
      'Figma-to-code automation prototypes to speed UI development',
      'Hands-on workshops and presentations for frontend teams',
      'Practical AI use-cases integrated into developer workflows',
      'Improved productivity and code quality through tooling adoption',
    ],
    imageUrl: '/images/projects/ai-learning/HomePage.png',
    images: [
      '/images/projects/ai-learning/HomePage.png',
      '/images/projects/ai-learning/UsecasePage.png',
      '/images/projects/ai-learning/UsecaseTwoPage.png',
      '/images/projects/ai-learning/UsecaseThreePage.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'AI',
    featured: true,
  },
  {
    id: '4',
    title: 'Banking Web Application',
    description:
      'Responsive banking platform with cost negotiation, card management, and campaign details.',
    technologies: ['React.js', 'JavaScript', 'Node.js', 'Express.js', 'Jest Testing Library'],
    features: [
      'Cost negotiation interface with expandable details',
      'Card management and addition',
      'Campaign and product details pages',
      'Responsive design for all devices',
      'Jest testing for reliability',
    ],
    imageUrl: '/images/projects/banking-app/home.png',
    images: [
      '/images/projects/banking-app/home.png',
      '/images/projects/banking-app/cost_negotiation.png',
      '/images/projects/banking-app/add_card.png',
      '/images/projects/banking-app/detalii_produs.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Web',
    featured: false,
  },
];

export const certificates: Certificate[] = [
  {
    id: '1',
    title: 'Meta React Native Certification',
    issuer: 'Meta via Coursera',
    date: 'March 2024',
    imageUrl: '/images/certificates/meta_react_native_certificate.png',
    credentialUrl: '',
  },
  {
    id: '2',
    title: 'React Native',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/react_native.png',
    credentialUrl: '',
  },
  {
    id: '3',
    title: 'Capstone React App',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/capstone_react_app.png',
    credentialUrl: '',
  },
  {
    id: '4',
    title: 'React Basics',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/react_basics.png',
    credentialUrl: '',
  },
  {
    id: '5',
    title: 'Introduction to Mobile Development',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/introduction_to_mobile_development.png',
    credentialUrl: '',
  },
  {
    id: '6',
    title: 'Programming with JavaScript',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/programming_with_javascript.png',
    credentialUrl: '',
  },
  {
    id: '7',
    title: 'Principles of UI/UX Design',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/principle_of_ui_ux.png',
    credentialUrl: '',
  },
  {
    id: '8',
    title: 'Version Control',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/version_control.png',
    credentialUrl: '',
  },
  {
    id: '9',
    title: 'Working with Data',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/working_with_data.png',
    credentialUrl: '',
  },
];

export const services: Service[] = [
  {
    id: 1,
    title: 'Web Development',
    description:
      'Full-stack web applications focused on performance and maintainability, using React.js, Next.js, Node.js, NestJS and modern best practices',
    icon: 'Code2',
  },
  {
    id: 2,
    title: 'Mobile Development',
    description:
      'Cross-platform mobile apps with React Native (Expo), published to Google Play and App Store, including IAP and OAuth integrations',
    icon: 'Smartphone',
  },
  {
    id: 3,
    title: 'AI Integration',
    description: 'Integrate AI features using OpenAI API, MCP servers, and custom AI solutions',
    icon: 'Brain',
  },
  {
    id: 4,
    title: 'CI/CD & DevOps',
    description:
      'Implemented CI/CD pipelines (GitHub Actions, Jenkins) and containerized deployments (Docker) reducing deployment time and improving release reliability',
    icon: 'Rocket',
  },
  {
    id: 5,
    title: 'Backend Development',
    description: 'Scalable backend APIs with Node.js, NestJS, Express.js',
    icon: 'Server',
  },
  {
    id: 6,
    title: 'Technical Consulting',
    description: 'Architecture design, code reviews, and best practices consultation',
    icon: 'Users',
  },
];

export const socialLinks: SocialLink[] = [
  {
    platform: 'GitHub',
    url: 'https://github.com/robertfloria',
    icon: 'github',
  },
  {
    platform: 'LinkedIn',
    url: 'https://www.linkedin.com/in/robert-nicolae-floria-51981920b/',
    icon: 'linkedin',
  },
  {
    platform: 'Email',
    url: 'mailto:robertfloria27@gmail.com',
    icon: 'mail',
  },
];
