import { Project } from "../types/Project";

export const projects: Project[] = [
  {
    id: '1',
    title: 'Mental Health Mobile App – AI Assistant',
    description:
      'Cross-platform mobile application (Expo) featuring an AI-powered chatbot for personalized mental health guidance, secure OAuth authentication, and in-app purchases. Published to Google Play and Apple App Store.',
    technologies: [
      'React Native (Expo)',
      'TypeScript',
      'OpenAI API',
      'Node.js',
      'Express.js',
      'Firebase',
      'OAuth 2.0',
      'Google Pay',
      'Apple Pay',
      'Railway',
      'Docker',
      'Jest Testing Library',
      'AWS S3',
      'CI-CD: GitHub Actions & Google Play Console & Apple App Store Connect',
    ],
    features: [
      'AI chatbot using OpenAI API for personalized mental health guidance',
      'Secure OAuth authentication (Google & Apple) with Firebase integration',
      'In-App Purchases and subscription flows using Google Pay and Apple Pay',
      'Backend containerized with Docker and deployed on Railway',
      'AWS S3 for media storage and Firebase Cloud Messaging for notifications',
      'Published to Google Play and Apple App Store',
    ],
    imageUrl: '/images/projects/mobile-app/mento_recommendation.png',
    images: [
      '/images/projects/mobile-app/home.png',
      '/images/projects/mobile-app/mento_presentation.png',
      '/images/projects/mobile-app/mento_recommendation.png',
      '/images/projects/mobile-app/chatbot.png',
      '/images/projects/mobile-app/breathing.png',
      '/images/projects/mobile-app/meditation.png',
      '/images/projects/mobile-app/charts.png',
      '/images/projects/mobile-app/logs.png',
      '/images/projects/mobile-app/awards.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Mobile',
    featured: true,
  },
  {
    id: '2',
    title: 'Guaranteed Loan Management System',
    description:
      'Microservices platform for secured loan management with compliance, automated origination, and risk scoring; focused on reliability and maintainability for financial environments.',
    technologies: [
      'React.js',
      'TypeScript',
      'ASP.NET Core',
      'SQL Server',
      'Jest Testing Library',
      'CI-CD: Jenkins',
    ],
    features: [
      'Automated loan origination and risk scoring',
      'Repayment tracking reducing manual workload by 40%',
      'CI/CD pipelines using Jenkins',
      'Microservices architecture for scalability',
      'Production-ready financial system with compliance',
    ],
    imageUrl: '/images/projects/loan-portfolio/HomePage.png',
    images: [
      '/images/projects/loan-portfolio/HomePage.png',
      '/images/projects/loan-portfolio/CreditRequestPage.png',
      '/images/projects/loan-portfolio/CreditDetailsPage.png',
      '/images/projects/loan-portfolio/Filters.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Web',
    featured: true,
  },
  {
    id: '3',
    title: 'AI Adoption Initiative for Frontend Teams',
    description:
      'Company-wide program to integrate AI tooling and workflows (Copilot, OpenAI) into frontend teams, including demos, automation and workshops to accelerate development.',
    technologies: [
      'React.js',
      'TypeScript',
      'GitHub Copilot',
      'MCP Servers',
      'OpenAI API',
      'Figma',
    ],
    features: [
      'Demo applications showcasing Copilot-assisted coding and AI-driven patterns',
      'Figma-to-code automation prototypes to speed UI development',
      'Hands-on workshops and presentations for frontend teams',
      'Practical AI use-cases integrated into developer workflows',
      'Improved productivity and code quality through tooling adoption',
    ],
    imageUrl: '/images/projects/ai-learning/HomePage.png',
    images: [
      '/images/projects/ai-learning/HomePage.png',
      '/images/projects/ai-learning/UsecasePage.png',
      '/images/projects/ai-learning/UsecaseTwoPage.png',
      '/images/projects/ai-learning/UsecaseThreePage.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'AI',
    featured: true,
  },
  {
    id: '4',
    title: 'Banking Web Application',
    description:
      'Responsive banking platform with cost negotiation, card management, and campaign details.',
    technologies: ['React.js', 'JavaScript', 'Node.js', 'Express.js', 'Jest Testing Library'],
    features: [
      'Cost negotiation interface with expandable details',
      'Card management and addition',
      'Campaign and product details pages',
      'Responsive design for all devices',
      'Jest testing for reliability',
    ],
    imageUrl: '/images/projects/banking-app/home.png',
    images: [
      '/images/projects/banking-app/home.png',
      '/images/projects/banking-app/cost_negotiation.png',
      '/images/projects/banking-app/add_card.png',
      '/images/projects/banking-app/detalii_produs.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: 'Web',
    featured: false,
  },
  {
    id: '5',
    title: 'Personal Portfolio (This Website)',
    description:
      'Personal portfolio showcasing projects, blog, and contact built with Next.js for the frontend and NestJS for the API. Demonstrates learning and integration of Next.js and NestJS, CI/CD with GitHub Actions, and modern deployment workflows.',
    technologies: [
      'Next.js',
      'NestJS',
      'TypeScript',
      'Tailwind CSS',
      'GitHub Actions',
      'Docker',
      'Node.js',
      'Jest Testing Library',
    ],
    features: [
      'Server-side rendering and static optimization with Next.js',
      'Backend API built with NestJS for contact/email handling',
      'CI/CD with GitHub Actions and Docker-based workflows',
      'Responsive design with Tailwind CSS and accessibility improvements',
      'Image optimization and performance tuning',
    ],
    imageUrl: '/images/projects/personal-portfolio/hero_section.png',
    images: [
      '/images/projects/personal-portfolio/hero_section.png',
      '/images/projects/personal-portfolio/about_section.png',
      '/images/projects/personal-portfolio/skills_section.png',
      '/images/projects/personal-portfolio/projects_section.png',
      '/images/projects/personal-portfolio/certificates_section.png',
      '/images/projects/personal-portfolio/timeline_section.png',
      '/images/projects/personal-portfolio/contact_section.png',
    ],
    githubUrl: 'https://github.com/robertfloria/personal-portofolio',
    liveUrl: '',
    category: 'Web',
    featured: true,
  },
];
