import { Project } from '../types/project';
import { PROJECT_CATEGORIES } from './constants';

export const projects: Project[] = [
  {
    id: '1',
    title: 'Derisqo - AI Document & Meeting Analysis Platform',
    description:
      'Built and launched an AI-powered SaaS for meeting transcription and contract analysis (public beta). Implemented contract risk analysis (11 clause categories), sentiment signals, and action-item extraction using OpenAI GPT-4o. Added production observability with Sentry (errors + performance), structured logs, and actionable alerts. Implemented secure authentication (JWT/cookie-based, Google OAuth, beta access control) and hardened APIs with rate limiting, validation, and secure webhook handling (idempotency). Redis-backed BullMQ for background jobs (email delivery, transcription pipeline, document analysis) with Server-Sent Events for real-time progress updates. Whisper-based transcription with automatic PII redaction for GDPR compliance. Stripe subscriptions, metered usage, and webhook-driven billing with operational tooling for reliable processing.',
    technologies: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'NestJS 11',
      'Prisma ORM 6',
      'PostgreSQL',
      'Redis',
      'BullMQ',
      'Tailwind CSS 4',
      'TanStack Query v5',
      'Zustand',
      'Zod',
      'Framer Motion',
      'OpenAI GPT-4o',
      'OpenAI Whisper',
      'FFmpeg',
      'Stripe',
      'JWT/OAuth2',
      'Sentry',
      'Docker',
      'Railway',
      'Turborepo',
      'pnpm',
      'GitHub Actions',
    ],
    features: [
      'AI contract analysis: 11 clause categories, sentiment signals, action-item extraction using GPT-4o',
      'Whisper-based transcription with audio/video support, automatic PII redaction (GDPR-friendly)',
      'Redis-backed BullMQ for background jobs (email, transcription, analysis) with retries/backoff',
      'Real-time processing updates via Server-Sent Events (SSE)',
      'Production observability: Sentry (error/performance tracking), structured logging, alerts',
      'Secure auth: JWT/HttpOnly cookies, Google OAuth, beta access control, rate limiting',
      'Stripe billing: subscriptions, metered usage, webhook-driven flows with idempotency',
      'API hardening: Zod validation, secure webhook signatures, OWASP mitigations (CSRF/XSS/CSP)',
      'Full-stack monorepo (pnpm, Turborepo) with shared components, Docker, CI/CD (GitHub Actions)',
    ],
    imageUrl: '/images/projects/ai-documents/hero.png',
    images: [
      '/images/projects/ai-documents/hero.png',
      '/images/projects/ai-documents/features_light.png',
      '/images/projects/ai-documents/how_it_works_light.png',
      '/images/projects/ai-documents/meeting_analysis_light.png',
      '/images/projects/ai-documents/document_analysis_light.png',
      '/images/projects/ai-documents/chat_light.png',
      '/images/projects/ai-documents/trust_and_security_light.png',
    ],
    githubUrl: '',
    liveUrl: 'https://derisqo.rbx-soft.tech/',
    category: PROJECT_CATEGORIES.AI,
    featured: true,
  },
  // {
  //   id: '2',
  //   title: 'MentoIQ - Mental Health Mobile App – AI Assistant',
  //   description:
  //     'Built a cross-platform mental health app with React Native (Expo), currently in internal testing phase. Integrated AI chatbot (OpenAI API) for personalized guidance, improving engagement and reducing manual support by 40%. Implemented secure authentication (OAuth for Google & Apple) and payment systems (Google Pay, Apple Pay, IAP). Deployed backend on Railway with Docker, integrated AWS S3 for media storage and Firebase for notifications. Achieved 99.9% uptime and optimized app performance for fast load times.',
  //   technologies: [
  //     'React Native (Expo)',
  //     'TypeScript',
  //     'OpenAI API',
  //     'Node.js',
  //     'Express.js',
  //     'Firebase',
  //     'OAuth 2.0',
  //     'Google Pay',
  //     'Apple Pay',
  //     'Railway',
  //     'Docker',
  //     'Jest Testing Library',
  //     'AWS S3',
  //     'CI-CD: GitHub Actions',
  //   ],
  //   features: [
  //     'Built a cross-platform app with React Native (Expo), currently in internal testing',
  //     'Integrated AI chatbot (OpenAI API) for personalized guidance, improving engagement and reducing manual support by 40%',
  //     'Implemented secure authentication (OAuth for Google & Apple) and payment systems (Google Pay, Apple Pay, IAP)',
  //     'Deployed backend on Railway with Docker, integrated AWS S3 for media storage and Firebase for notifications',
  //     'Achieved 99.9% uptime and optimized app performance for fast load times',
  //   ],
  //   imageUrl: '/images/projects/mobile-app/mento_recommendation.png',
  //   images: [
  //     '/images/projects/mobile-app/home.png',
  //     '/images/projects/mobile-app/mento_presentation.png',
  //     '/images/projects/mobile-app/mento_recommendation.png',
  //     '/images/projects/mobile-app/chatbot.png',
  //     '/images/projects/mobile-app/breathing.png',
  //     '/images/projects/mobile-app/meditation.png',
  //     '/images/projects/mobile-app/charts.png',
  //     '/images/projects/mobile-app/logs.png',
  //     '/images/projects/mobile-app/awards.png',
  //   ],
  //   githubUrl: '',
  //   liveUrl: '',
  //   category: PROJECT_CATEGORIES.MOBILE,
  //   featured: true,
  // },
  {
    id: '3',
    title: 'Guaranteed Loan Management System',
    description:
      'Designed and implemented a microservices-based platform for managing secured loans, ensuring compliance and operational efficiency. Automated loan origination, risk scoring, and repayment tracking, reducing manual workload by 40%. Built CI/CD pipelines using Jenkins, enabling fast and reliable deployments. Impact: Delivered a robust financial system used in production, strengthening expertise in regulated environments and scalable architectures.',
    technologies: [
      'React.js',
      'TypeScript',
      'ASP.NET Core',
      'SQL Server',
      'Jest Testing Library',
      'CI-CD: Jenkins',
    ],
    features: [
      'Designed and implemented a microservices-based platform for managing secured loans',
      'Automated loan origination, risk scoring, and repayment tracking, reducing manual workload by 40%',
      'Built CI/CD pipelines using Jenkins for fast and reliable deployments',
      'Impact: Delivered a robust financial system used in production, strengthening expertise in regulated environments and scalable architectures',
    ],
    imageUrl: '/images/projects/loan-portfolio/HomePage.png',
    images: [
      '/images/projects/loan-portfolio/HomePage.png',
      '/images/projects/loan-portfolio/CreditRequestPage.png',
      '/images/projects/loan-portfolio/CreditDetailsPage.png',
      '/images/projects/loan-portfolio/Filters.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.WEB,
    featured: true,
  },
  {
    id: '4',
    title: 'AI Adoption Initiative for Frontend Teams',
    description:
      'Led AI integration across React.js frontend teams, improving productivity and reducing repetitive coding tasks by 30%, positioning the company as an early adopter of AI-driven development. Developed a custom demo app and presentation showcasing Copilot-assisted coding, Figma-to-code automation, and interactive AI use cases for React developers. Conducted technical workshops and presentations to accelerate adoption and improve code quality across multiple teams. Impact: Faster development cycles, improved maintainability, and enhanced team efficiency.',
    technologies: [
      'React.js',
      'TypeScript',
      'GitHub Copilot',
      'MCP Servers',
      'OpenAI API',
      'Figma',
    ],
    features: [
      'Led AI integration across React.js frontend teams, improving productivity and reducing repetitive coding tasks by 30%',
      'Developed a custom demo app and presentation showcasing Copilot-assisted coding, Figma-to-code automation, and interactive AI use cases',
      'Conducted technical workshops and presentations to accelerate adoption and improve code quality',
      'Impact: Faster development cycles, improved maintainability, and enhanced team efficiency',
    ],
    imageUrl: '/images/projects/ai-learning/HomePage.png',
    images: [
      '/images/projects/ai-learning/HomePage.png',
      '/images/projects/ai-learning/UsecasePage.png',
      '/images/projects/ai-learning/UsecaseTwoPage.png',
      '/images/projects/ai-learning/UsecaseThreePage.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.AI,
    featured: true,
  },
  {
    id: '5',
    title: 'Responsive Banking Platform',
    description:
      'Built a responsive web platform for cost negotiation, card management, and campaign/product details, optimized for mobile and desktop usage. Implemented a cost negotiation interface with expandable detail views and predictable UI state handling for complex workflows. Developed card management flows (add/manage cards) and integrated backend endpoints using Node.js/Express. Added automated test coverage with Jest and React Testing Library to improve reliability and prevent regressions. Delivered in enterprise environment with production releases.',
    technologies: [
      'React.js',
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Express.js',
      'Jest Testing Library',
      'React Testing Library',
      'CI-CD: Jenkins',
    ],
    features: [
      'Responsive web platform optimized for mobile and desktop usage',
      'Cost negotiation interface with expandable detail views and predictable UI state handling',
      'Card management flows: add/manage cards with backend integration (Node.js/Express)',
      'Campaign and product details pages with dynamic content',
      'Automated test coverage with Jest and React Testing Library to prevent regressions',
      'Delivered in enterprise environment with production releases',
    ],
    imageUrl: '/images/projects/banking-app/home.png',
    images: [
      '/images/projects/banking-app/home.png',
      '/images/projects/banking-app/cost_negotiation.png',
      '/images/projects/banking-app/add_card.png',
      '/images/projects/banking-app/detalii_produs.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.WEB,
    featured: true,
  },
];
