import { Project } from '../types/project';
import { PROJECT_CATEGORIES } from './constants';

export const projects: Project[] = [
  {
    id: '1',
    title: 'MentoIQ - Mental Health Mobile App – AI Assistant',
    description:
      'Built a cross-platform app with React Native (Expo), deployed on Google Play & App Store. Integrated AI chatbot (OpenAI API) for personalized guidance, improving engagement and reducing manual support by 40%. Implemented secure authentication (OAuth for Google & Apple) and payment systems (Google Pay, Apple Pay, IAP). Deployed backend on Railway with Docker, integrated AWS S3 for media storage and Firebase for notifications. Achieved 99.9% uptime and optimized app performance for fast load times.',
    technologies: [
      'React Native (Expo)',
      'TypeScript',
      'OpenAI API',
      'Node.js',
      'Express.js',
      'Firebase',
      'OAuth 2.0',
      'Google Pay',
      'Apple Pay',
      'Railway',
      'Docker',
      'Jest Testing Library',
      'AWS S3',
      'CI-CD: GitHub Actions & Google Play Console & Apple App Store Connect',
    ],
    features: [
      'Built a cross-platform app with React Native (Expo), deployed on Google Play & App Store',
      'Integrated AI chatbot (OpenAI API) for personalized guidance, improving engagement and reducing manual support by 40%',
      'Implemented secure authentication (OAuth for Google & Apple) and payment systems (Google Pay, Apple Pay, IAP)',
      'Deployed backend on Railway with Docker, integrated AWS S3 for media storage and Firebase for notifications',
      'Achieved 99.9% uptime and optimized app performance for fast load times',
    ],
    imageUrl: '/images/projects/mobile-app/mento_recommendation.png',
    images: [
      '/images/projects/mobile-app/home.png',
      '/images/projects/mobile-app/mento_presentation.png',
      '/images/projects/mobile-app/mento_recommendation.png',
      '/images/projects/mobile-app/chatbot.png',
      '/images/projects/mobile-app/breathing.png',
      '/images/projects/mobile-app/meditation.png',
      '/images/projects/mobile-app/charts.png',
      '/images/projects/mobile-app/logs.png',
      '/images/projects/mobile-app/awards.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.MOBILE,
    featured: true,
  },
  {
    id: '2',
    title: 'Guaranteed Loan Management System',
    description:
      'Designed and implemented a microservices-based platform for managing secured loans, ensuring compliance and operational efficiency. Automated loan origination, risk scoring, and repayment tracking, reducing manual workload by 40%. Built CI/CD pipelines using Jenkins, enabling fast and reliable deployments. Impact: Delivered a robust financial system used in production, strengthening expertise in regulated environments and scalable architectures.',
    technologies: [
      'React.js',
      'TypeScript',
      'ASP.NET Core',
      'SQL Server',
      'Jest Testing Library',
      'CI-CD: Jenkins',
    ],
    features: [
      'Designed and implemented a microservices-based platform for managing secured loans',
      'Automated loan origination, risk scoring, and repayment tracking, reducing manual workload by 40%',
      'Built CI/CD pipelines using Jenkins for fast and reliable deployments',
      'Impact: Delivered a robust financial system used in production, strengthening expertise in regulated environments and scalable architectures',
    ],
    imageUrl: '/images/projects/loan-portfolio/HomePage.png',
    images: [
      '/images/projects/loan-portfolio/HomePage.png',
      '/images/projects/loan-portfolio/CreditRequestPage.png',
      '/images/projects/loan-portfolio/CreditDetailsPage.png',
      '/images/projects/loan-portfolio/Filters.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.WEB,
    featured: true,
  },
  {
    id: '3',
    title: 'AI Adoption Initiative for Frontend Teams',
    description:
      'Led AI integration across React.js frontend teams, improving productivity and reducing repetitive coding tasks by 30%, positioning the company as an early adopter of AI-driven development. Developed a custom demo app and presentation showcasing Copilot-assisted coding, Figma-to-code automation, and interactive AI use cases for React developers. Conducted technical workshops and presentations to accelerate adoption and improve code quality across multiple teams. Impact: Faster development cycles, improved maintainability, and enhanced team efficiency.',
    technologies: [
      'React.js',
      'TypeScript',
      'GitHub Copilot',
      'MCP Servers',
      'OpenAI API',
      'Figma',
    ],
    features: [
      'Led AI integration across React.js frontend teams, improving productivity and reducing repetitive coding tasks by 30%',
      'Developed a custom demo app and presentation showcasing Copilot-assisted coding, Figma-to-code automation, and interactive AI use cases',
      'Conducted technical workshops and presentations to accelerate adoption and improve code quality',
      'Impact: Faster development cycles, improved maintainability, and enhanced team efficiency',
    ],
    imageUrl: '/images/projects/ai-learning/HomePage.png',
    images: [
      '/images/projects/ai-learning/HomePage.png',
      '/images/projects/ai-learning/UsecasePage.png',
      '/images/projects/ai-learning/UsecaseTwoPage.png',
      '/images/projects/ai-learning/UsecaseThreePage.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.AI,
    featured: true,
  },
  {
    id: '4',
    title: 'Banking Web Application',
    description:
      'Responsive banking platform with cost negotiation, card management, and campaign details.',
    technologies: ['React.js', 'JavaScript', 'Node.js', 'Express.js', 'Jest Testing Library'],
    features: [
      'Cost negotiation interface with expandable details',
      'Card management and addition',
      'Campaign and product details pages',
      'Responsive design for all devices',
      'Jest testing for reliability',
    ],
    imageUrl: '/images/projects/banking-app/home.png',
    images: [
      '/images/projects/banking-app/home.png',
      '/images/projects/banking-app/cost_negotiation.png',
      '/images/projects/banking-app/add_card.png',
      '/images/projects/banking-app/detalii_produs.png',
    ],
    githubUrl: '',
    liveUrl: '',
    category: PROJECT_CATEGORIES.WEB,
    featured: false,
  },
  {
    id: '5',
    title: 'Personal Portfolio (This Website)',
    description:
      'Server-side rendering and static optimization with Next.js. Backend API built with NestJS for contact/email handling. CI/CD with GitHub Actions and Docker-based workflows. Responsive design with Tailwind CSS and accessibility improvements. Image optimization and performance tuning.',
    technologies: [
      'Next.js',
      'NestJS',
      'TypeScript',
      'Tailwind CSS',
      'GitHub Actions',
      'Docker',
      'Node.js',
      'Jest Testing Library',
    ],
    features: [
      'Server-side rendering and static optimization with Next.js',
      'Backend API built with NestJS for email/download cv handling',
      'CI/CD with GitHub Actions and Docker-based workflows',
      'Responsive design with Tailwind CSS and accessibility improvements',
      'Image optimization and performance tuning',
    ],
    imageUrl: '/images/projects/personal-portfolio/hero_section.png',
    images: [
      '/images/projects/personal-portfolio/hero_section.png',
      '/images/projects/personal-portfolio/about_section.png',
      '/images/projects/personal-portfolio/skills_section.png',
      '/images/projects/personal-portfolio/projects_section.png',
      '/images/projects/personal-portfolio/certificates_section.png',
      '/images/projects/personal-portfolio/timeline_section.png',
      '/images/projects/personal-portfolio/contact_section.png',
    ],
    githubUrl: 'https://github.com/robertfloria/personal-portofolio',
    liveUrl: '',
    category: PROJECT_CATEGORIES.WEB,
    featured: true,
  },
];
