import { Skill } from '../types/skill';
import { SKILLS_CATEGORIES } from './constants';

export const categories: Record<Skill['category'], string> = {
  Frontend: 'Frontend Development',
  Backend: 'Backend Development',
  DevOps: 'DevOps & Cloud',
  AI: 'AI & Integration',
  Tools: 'Tools & Productivity',
};

export const skills: Skill[] = [
  {
    name: 'React.js',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Fullscreen',
    yearsOfExperience: 4,
  },
  {
    name: 'Next.js',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Layout',
    yearsOfExperience: 2,
  },
  {
    name: 'React Native (Expo)',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Smartphone',
    yearsOfExperience: 2,
  },
  {
    name: 'TypeScript',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 4,
  },
  {
    name: 'JavaScript',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 5,
  },
  {
    name: 'HTML5 & CSS/SASS',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Code2',
    yearsOfExperience: 5,
  },
  {
    name: 'Tailwind CSS',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Code2',
    yearsOfExperience: 2,
  },
  {
    name: 'Node.js',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 4,
  },
  {
    name: 'NestJS',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 2,
  },
  {
    name: 'Express.js',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 4,
  },
  {
    name: 'Prisma ORM',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Database',
    yearsOfExperience: 2,
  },
  {
    name: 'ASP.NET Core',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'SQL Server',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 4,
  },
  {
    name: 'PostgreSQL',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 4,
  },
  {
    name: 'MySQL',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 4,
  },
  {
    name: 'Jest',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'TestTube',
    yearsOfExperience: 4,
  },
  {
    name: 'Testing Library',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'TestTube',
    yearsOfExperience: 3,
  },
  {
    name: 'Docker',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 2,
  },
  {
    name: 'AWS S3',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Railway',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Vercel',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Firebase',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'GitHub Actions',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 90,
    iconKey: 'GitBranch',
    yearsOfExperience: 2,
  },
  {
    name: 'Jenkins',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'GitBranch',
    yearsOfExperience: 3,
  },
  {
    name: 'OpenAI API',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 90,
    iconKey: 'Bot',
    yearsOfExperience: 2,
  },
  {
    name: 'Stripe',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 85,
    iconKey: 'CreditCard',
    yearsOfExperience: 1.5,
  },
  // Tools
  {
    name: 'TanStack React Query',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 90,
    iconKey: 'Code',
    yearsOfExperience: 2,
  },
  {
    name: 'Turborepo',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 1.5,
  },
  {
    name: 'GitHub Copilot',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 90,
    iconKey: 'Github',
    yearsOfExperience: 2,
  },
  {
    name: 'MCP Servers',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Prompt Engineering',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 90,
    iconKey: 'Edit3',
    yearsOfExperience: 2,
  },
];
