import { Skill } from '../types/skill';

export const categories: Record<Skill['category'], string> = {
  Frontend: 'Frontend Development',
  Backend: 'Backend Development',
  DevOps: 'DevOps & Cloud',
  AI: 'AI & Integration',
  Tools: 'Tools & Productivity',
};

export const skills: Skill[] = [
  {
    name: 'React.js',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Fullscreen',
    yearsOfExperience: 3.5,
  },
  {
    name: 'Next.js',
    category: 'Frontend',
    proficiency: 90,
    iconKey: 'Layout',
    yearsOfExperience: 1,
  },
  {
    name: 'React Native (Expo)',
    category: 'Frontend',
    proficiency: 90,
    iconKey: 'Smartphone',
    yearsOfExperience: 1.5,
  },
  {
    name: 'TypeScript',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 3,
  },
  {
    name: 'JavaScript',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 4,
  },
  {
    name: 'HTML5 & CSS/SASS',
    category: 'Frontend',
    proficiency: 95,
    iconKey: 'Code2',
    yearsOfExperience: 4,
  },
  {
    name: 'Node.js',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'NestJS',
    category: 'Backend',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 1,
  },
  {
    name: 'ASP.NET Core',
    category: 'Backend',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'SQL Server',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 3,
  },
  {
    name: 'MySQL',
    category: 'Backend',
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 3,
  },
  {
    name: 'Docker',
    category: 'DevOps',
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 1,
  },
  {
    name: 'GitHub Actions',
    category: 'DevOps',
    proficiency: 90,
    iconKey: 'GitBranch',
    yearsOfExperience: 1,
  },
  {
    name: 'Jenkins',
    category: 'DevOps',
    proficiency: 85,
    iconKey: 'GitBranch',
    yearsOfExperience: 2,
  },
  {
    name: 'OpenAI API',
    category: 'AI',
    proficiency: 90,
    iconKey: 'Bot',
    yearsOfExperience: 1,
  },
  // Tools
  {
    name: 'GitHub Copilot',
    category: 'Tools',
    proficiency: 90,
    iconKey: 'Github',
    yearsOfExperience: 1,
  },
  {
    name: 'MCP Servers',
    category: 'Tools',
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 1,
  },
  {
    name: 'Prompt Engineering',
    category: 'Tools',
    proficiency: 90,
    iconKey: 'Edit3',
    yearsOfExperience: 1,
  },
];
