import { Skill } from '../types/skill';
import { SKILLS_CATEGORIES } from './constants';

export const categories: Record<Skill['category'], string> = {
  Frontend: 'Frontend Development',
  Backend: 'Backend Development',
  DevOps: 'DevOps & Cloud',
  AI: 'AI & Integration',
  Tools: 'Tools & Productivity',
};

export const skills: Skill[] = [
  {
    name: 'React 19',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Fullscreen',
    yearsOfExperience: 5,
  },
  {
    name: 'Next.js 16',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Layout',
    yearsOfExperience: 2,
  },
  {
    name: 'TypeScript',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 95,
    iconKey: 'Code',
    yearsOfExperience: 5,
  },
  {
    name: 'TanStack Query',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Code',
    yearsOfExperience: 2,
  },
  {
    name: 'Zustand',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Zod',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Shield',
    yearsOfExperience: 2,
  },
  {
    name: 'Tailwind CSS',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Code2',
    yearsOfExperience: 2,
  },
  {
    name: 'Framer Motion',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 85,
    iconKey: 'Zap',
    yearsOfExperience: 2,
  },
  {
    name: 'Radix UI',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 85,
    iconKey: 'Component',
    yearsOfExperience: 1.5,
  },
  {
    name: 'React Native (Expo)',
    category: SKILLS_CATEGORIES.FRONTEND,
    proficiency: 90,
    iconKey: 'Smartphone',
    yearsOfExperience: 2,
  },
  {
    name: 'Node.js',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 5,
  },
  {
    name: 'NestJS 11',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 2,
  },
  {
    name: 'Express',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Server',
    yearsOfExperience: 5,
  },
  {
    name: 'GraphQL',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 80,
    iconKey: 'Share2',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Prisma ORM',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 2,
  },
  {
    name: 'Zod Validation',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Shield',
    yearsOfExperience: 2,
  },
  {
    name: 'ASP.NET Core',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 3,
  },
  {
    name: 'SQL Server',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 4,
  },
  {
    name: 'PostgreSQL',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 4,
  },
  {
    name: 'MySQL',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 90,
    iconKey: 'Database',
    yearsOfExperience: 5,
  },
  {
    name: 'MongoDB',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Database',
    yearsOfExperience: 2,
  },
  {
    name: 'Redis',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Database',
    yearsOfExperience: 1.5,
  },
  {
    name: 'BullMQ',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'Layers',
    yearsOfExperience: 1.5,
  },
  {
    name: 'WebSockets',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 80,
    iconKey: 'Radio',
    yearsOfExperience: 2,
  },
  {
    name: 'Vitest',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'TestTube',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Jest',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'TestTube',
    yearsOfExperience: 5,
  },
  {
    name: 'Testing Library',
    category: SKILLS_CATEGORIES.BACKEND,
    proficiency: 85,
    iconKey: 'TestTube',
    yearsOfExperience: 4,
  },
  {
    name: 'Docker',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 2,
  },
  {
    name: 'AWS S3',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Railway',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Vercel',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'Firebase',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'Cloud',
    yearsOfExperience: 2,
  },
  {
    name: 'GitHub Actions',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 90,
    iconKey: 'GitBranch',
    yearsOfExperience: 2,
  },
  {
    name: 'Jenkins',
    category: SKILLS_CATEGORIES.DEVOPS,
    proficiency: 85,
    iconKey: 'GitBranch',
    yearsOfExperience: 3,
  },
  {
    name: 'OpenAI GPT-4o',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 90,
    iconKey: 'Bot',
    yearsOfExperience: 2,
  },
  {
    name: 'Whisper API',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 85,
    iconKey: 'Mic',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Sentry',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 85,
    iconKey: 'Activity',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Stripe',
    category: SKILLS_CATEGORIES.AI,
    proficiency: 90,
    iconKey: 'CreditCard',
    yearsOfExperience: 2,
  },
  // Tools
  {
    name: 'Turborepo',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 85,
    iconKey: 'Box',
    yearsOfExperience: 2,
  },
  {
    name: 'pnpm',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 85,
    iconKey: 'Package',
    yearsOfExperience: 2,
  },
  {
    name: 'GitHub Copilot',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 90,
    iconKey: 'Github',
    yearsOfExperience: 2,
  },
  {
    name: 'MCP Servers',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 85,
    iconKey: 'Server',
    yearsOfExperience: 1.5,
  },
  {
    name: 'Prompt Engineering',
    category: SKILLS_CATEGORIES.TOOLS,
    proficiency: 90,
    iconKey: 'Edit3',
    yearsOfExperience: 2,
  },
];
