import { CertificateItem } from '../types/certificate-item';

export const certificates: CertificateItem[] = [
  {
    id: '1',
    title: 'Meta React Native Certification',
    issuer: 'Meta via Coursera',
    date: 'March 2024',
    imageUrl: '/images/certificates/meta_react_native_certificate.png',
    credentialUrl: '',
  },
  {
    id: '2',
    title: 'React Native',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/react_native.png',
    credentialUrl: '',
  },
  {
    id: '3',
    title: 'Capstone React App',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/capstone_react_app.png',
    credentialUrl: '',
  },
  {
    id: '4',
    title: 'React Basics',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/react_basics.png',
    credentialUrl: '',
  },
  {
    id: '5',
    title: 'Introduction to Mobile Development',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/introduction_to_mobile_development.png',
    credentialUrl: '',
  },
  {
    id: '6',
    title: 'Programming with JavaScript',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/programming_with_javascript.png',
    credentialUrl: '',
  },
  {
    id: '7',
    title: 'Principles of UI/UX Design',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/principle_of_ui_ux.png',
    credentialUrl: '',
  },
  {
    id: '8',
    title: 'Version Control',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/version_control.png',
    credentialUrl: '',
  },
  {
    id: '9',
    title: 'Working with Data',
    issuer: 'Meta via Coursera',
    date: '2024',
    imageUrl: '/images/certificates/working_with_data.png',
    credentialUrl: '',
  },
];
